curl --location --request GET 'http://10.100.3.137:8088/' \
--header 'Content-Type: application/xml' \
--data '<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/">
    <soapenv:Header>
        <ns1:ibsinfo xmlns:ns1="urn:schemas-iwaysoftware-com:iwse">
            <ns1:service>InvoiceImport_V1</ns1:service>
            <ns1:method>Z_ARIBA_BAPI_PO_CREATE</ns1:method>
            <ns1:license>test</ns1:license>
            <ns1:Username>ARIBA_CPIC</ns1:Username>
            <ns1:Password>ENCR(312531493234280318631613211321732473227321431973252)</ns1:Password>
        </ns1:ibsinfo>
    </soapenv:Header>
    <soap:Body xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
        <ns0:Z_ARIBA_BAPI_PO_CREATE xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ns0="urn:iwaysoftware:ibse:jul2003:Z_ARIBA_BAPI_PO_CREATE">
  <ns0:Z_ARIBA_BAPI_PO_CREATE>
    <ns0:PARTITION>par1iam</ns0:PARTITION>
    <ns0:PO_HEADER>
      <ns0:DOC_DATE>2023/04/14</ns0:DOC_DATE>
      <ns0:PURCH_ORG>Z001</ns0:PURCH_ORG>
      <ns0:PUR_GROUP>008</ns0:PUR_GROUP>
      <ns0:VENDOR>0000010560</ns0:VENDOR>
      <ns0:PO_NUMBER>1005035491</ns0:PO_NUMBER>
      <ns0:ARIBA_DOC_TYPE>ZARD</ns0:ARIBA_DOC_TYPE>
      <ns0:ERPORDERID>1005035491</ns0:ERPORDERID>
    </ns0:PO_HEADER>
    <ns0:PO_HEADER_ADD_DATA>
      <ns0:PMNTTRMS>Z001</ns0:PMNTTRMS>
      <ns0:CURRENCY>MAD</ns0:CURRENCY>
      <ns0:OUR_REF>1005035491</ns0:OUR_REF>
    </ns0:PO_HEADER_ADD_DATA>
    <ns0:VARIANT>var1iam</ns0:VARIANT>
    <ns0:PO_COND>
      <ns0:item>
        <ns0:KSCHL>RA00</ns0:KSCHL>
        <ns0:KBETR>0</ns0:KBETR>
      </ns0:item>
      <ns0:item>
        <ns0:KSCHL>HB01</ns0:KSCHL>
        <ns0:KBETR>0</ns0:KBETR>
      </ns0:item>
    </ns0:PO_COND>
    <ns0:PO_ITEMS>
      <ns0:item>
        <ns0:PO_ITEM>00001</ns0:PO_ITEM>
        <ns0:MATERIAL/>
        <ns0:PUR_MAT/>
        <ns0:ITEM_CAT/>
        <ns0:ACCTASSCAT>K</ns0:ACCTASSCAT>
        <ns0:STORE_LOC>5000</ns0:STORE_LOC>
        <ns0:MAT_GRP>40000002</ns0:MAT_GRP>
        <ns0:SHORT_TEXT>test2</ns0:SHORT_TEXT>
        <ns0:DISTRIB/>
        <ns0:PART_INV/>
        <ns0:PLANT>Z000</ns0:PLANT>
        <ns0:UNIT>L</ns0:UNIT>
        <ns0:NET_PRICE>15.00000</ns0:NET_PRICE>
        <ns0:PRICE_UNIT>1</ns0:PRICE_UNIT>
        <ns0:REQ_ID>PR493175</ns0:REQ_ID>
        <ns0:ITEMONREQ>4</ns0:ITEMONREQ>
      </ns0:item>
    </ns0:PO_ITEMS>
    <ns0:PO_ITEM_ACCOUNT_ASSIGNMENT>
      <ns0:item>
        <ns0:PO_ITEM>00001</ns0:PO_ITEM>
        <ns0:SERIAL_NO>1</ns0:SERIAL_NO>
        <ns0:QUANTITY>18.00000</ns0:QUANTITY>
        <ns0:DISTR_PERC>0</ns0:DISTR_PERC>
        <ns0:G_L_ACCT>0061223001</ns0:G_L_ACCT>
        <ns0:COST_CTR>2221010100</ns0:COST_CTR>
        <ns0:ASSET_NO/>
        <ns0:SUB_NUMBER/>
        <ns0:ORDER_NO/>
        <ns0:WBS_ELEM_E/>
      </ns0:item>
    </ns0:PO_ITEM_ACCOUNT_ASSIGNMENT>
    <ns0:PO_ITEM_ADD_DATA>
      <ns0:item>
        <ns0:OVERDELTOL/>
        <ns0:UNDER_TOL/>
        <ns0:PO_ITEM>00001</ns0:PO_ITEM>
      </ns0:item>
    </ns0:PO_ITEM_ADD_DATA>
    <ns0:PO_ITEM_SCHEDULES>
      <ns0:item>
        <ns0:PO_ITEM>00001</ns0:PO_ITEM>
        <ns0:DELIV_DATE>2023/04/29</ns0:DELIV_DATE>
        <ns0:QUANTITY>18.00000</ns0:QUANTITY>
        <ns0:PREQ_ITEM>0</ns0:PREQ_ITEM>
      </ns0:item>
    </ns0:PO_ITEM_SCHEDULES>
    <ns0:PO_ITEM_TEXT>
      <ns0:item>
        <ns0:PO_NUMBER>0</ns0:PO_NUMBER>
        <ns0:PO_ITEM>00001</ns0:PO_ITEM>
        <ns0:TEXT_ID>F04</ns0:TEXT_ID>
        <ns0:TEXT_FORM/>
        <ns0:TEXT_LINE>Ariba Requisition:  PR493175</ns0:TEXT_LINE>
      </ns0:item>
      <ns0:item>
        <ns0:PO_NUMBER>1</ns0:PO_NUMBER>
        <ns0:PO_ITEM>00001</ns0:PO_ITEM>
        <ns0:TEXT_ID>F04</ns0:TEXT_ID>
        <ns0:TEXT_FORM/>
        <ns0:TEXT_LINE>Line Item:  4</ns0:TEXT_LINE>
      </ns0:item>
      <ns0:item>
        <ns0:PO_NUMBER>0</ns0:PO_NUMBER>
        <ns0:PO_ITEM>00000</ns0:PO_ITEM>
        <ns0:TEXT_ID>F09</ns0:TEXT_ID>
        <ns0:TEXT_FORM/>
        <ns0:TEXT_LINE>[-]</ns0:TEXT_LINE>
      </ns0:item>
      <ns0:item>
        <ns0:PO_NUMBER>0</ns0:PO_NUMBER>
        <ns0:PO_ITEM>00000</ns0:PO_ITEM>
        <ns0:TEXT_ID>F24</ns0:TEXT_ID>
        <ns0:TEXT_FORM/>
        <ns0:TEXT_LINE>0</ns0:TEXT_LINE>
      </ns0:item>
      <ns0:item>
        <ns0:PO_NUMBER>0</ns0:PO_NUMBER>
        <ns0:PO_ITEM>00000</ns0:PO_ITEM>
        <ns0:TEXT_ID>F17</ns0:TEXT_ID>
        <ns0:TEXT_FORM/>
        <ns0:TEXT_LINE>[-]</ns0:TEXT_LINE>
      </ns0:item>
      <ns0:item>
        <ns0:PO_NUMBER>0</ns0:PO_NUMBER>
        <ns0:PO_ITEM>00000</ns0:PO_ITEM>
        <ns0:TEXT_ID>F23</ns0:TEXT_ID>
        <ns0:TEXT_FORM/>
        <ns0:TEXT_LINE>Aucun</ns0:TEXT_LINE>
      </ns0:item>
      <ns0:item>
        <ns0:PO_NUMBER>0</ns0:PO_NUMBER>
        <ns0:PO_ITEM>00000</ns0:PO_ITEM>
        <ns0:TEXT_ID>F02</ns0:TEXT_ID>
        <ns0:TEXT_FORM/>
        <ns0:TEXT_LINE>Prepared by Siham Gadhi  [s.gadhi@iam.ma] (tel bureau:  ; tel mobile : )</ns0:TEXT_LINE>
      </ns0:item>
    </ns0:PO_ITEM_TEXT>
    <ns0:PO_ZZIMMOS>
      <ns0:item>
        <ns0:EBELP>00001</ns0:EBELP>
        <ns0:UMSON>X</ns0:UMSON>
        <ns0:PRIXNUL>15.00000</ns0:PRIXNUL>
        <ns0:ZZIMMOS/>
      </ns0:item>
    </ns0:PO_ZZIMMOS>
  </ns0:Z_ARIBA_BAPI_PO_CREATE>
</ns0:Z_ARIBA_BAPI_PO_CREATE>
    </soap:Body>
</soapenv:Envelope>'
